name: Publish NuGet Package

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET Core SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' # Use your targeted .NET version

    # Restore NuGet packages
    - name: Restore dependencies
      run: dotnet restore

    # Build the project with debug symbols
    - name: Build the project
      run: dotnet build --configuration Debug /p:DebugType=portable /p:DebugSymbols=true

    # Pack the project and include debug symbols in the NuGet package (.snupkg)
    - name: Pack NuGet package
      run: dotnet pack --configuration Debug --include-symbols --include-source -o ./artifacts

    # Push the NuGet package and symbols to the feed
    - name: Publish to NuGet feed
      run: dotnet nuget push "./artifacts/*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://nuget.pkg.github.com/JC-85/index.json --skip-duplicate
